### ISSUE TITLE
Not working at Ubuntu

### ISSUE THREAD

**Issue by axnsantana** [openearth/nefis-python#1]
Hi,

First of all, thanks for the package!
But I do not know if you did this package to unix environment, it is not working.
I looked at: https://pypi.python.org/pypi/nefis and the problem is the same.

First, the setup can not find the nefis library.
Is there some manual? or trick?

I saw parameters for Windows (like dll reference) inside of the setup.py.

**Comment by SiggyF** [comment]
There are [wheel](http://wheel.readthedocs.io/en/latest/) files available for windows with python2.7. We did not create wheel files for other platforms. I'll update the docs on how to build for linux and OSX.  
The source for the nefis library can be obtained from [delft3d](http://oss.deltares.nl).

**Comment by juanfcocontreras** [comment]
Are the documentation already updated for linux and osx?

Thanks!

**Comment by SiggyF** [comment]
I've got some code ready in the package upgrade Branch
 I was waiting for a review from @mooiman.

**Comment by juanfcocontreras** [comment]
Thanks @SiggyF. I've tried to compile nefis in linux and I got this error:

`configure: error: cannot find sources (plugins_qt/packages/dido/dido/dido.f90) in . or ..`

I've downloaded nefis from [https://svn.oss.deltares.nl/repos/delft3d/trunk/src/utils_lgpl/nefis](url), is that ok or am I doing something wrong?

**Comment by SiggyF** [comment]
Hi @juanfcocontreras. That is indeed the sourcecode repository that contains nefis.  Usually people install nefis as part of Delft3D. Details on compilation of Delft3D are described on the [oss deltares](https://oss.deltares.nl/web/delft3d/source-code) website.

**Comment by juanfcocontreras** [comment]
Ok, I could compile nefis, and it produces libNefisSO.so.0.0.0 and two symbolic links to it (libNefisSO.so and libNefisSO.so.0). If I add the folder to the setup.cfg file:

`library-dirs=/home/delft3d/src/utils_lgpl/nefis/packages/nefis/src_so/.libs/lib
`

I can't create the wheel: `/usr/bin/ld: cannot find -lnefis`

If I create a symbolic link from libnefis.so to libNefisSO.so.0.0.0 I can compile the wheel, but it doesn't include any libnefis*.so. So when I try to import `import nefis.cnefis` I get the following error:

`ImportError: libNefisSO.so.0: cannot open shared object file: No such file or directory`

Do you know what is wrong?

Thanks!

**Comment by juanfcocontreras** [comment]
I forgot to mention that I tried to copy directly `libNefisSO.so.0` to the nefis folder in the site-packages with no luck. I also tried the `inplace=1` in the `[build_ext]` setup.cfg section.

**Comment by SiggyF** [comment]
I thought that Delft3D generated a libnefis.so, but it seems to always build libNefisSo.so. Until I find what the "correct" name is you can use the symlink approach. The location of libnefis.so should be available at runtime. This is done by either setting `LD_LIBRARY_PATH=/opt/delft3d/..../lib` for linux or `DYLD_LIBRARY_PATH=/opt/delft3d/..../lib` for OSX.

**Comment by mooiman** [comment]
For now the library is named libNefisSO.so. We will consider another name for the NEFIS-library in future.
